### ISSUE TITLE
Problem of results -  not the same as presented in the paper

### ISSUE THREAD

**Issue by vickyyu90** [Dongjiahua/VICA-NeRF#1]
Hi,
I tried to use a text prompt 'turn him into a robot' as depicted in the repo to run it. The results turned out to be so blurry and did not follow the prompt correctly. Is there any hyperparameter I need to edit?

Thanks!

**Comment by vickyyu90** [comment]
I used default parameters, the results looked like this:
![frame_00032](https://github.com/Dongjiahua/VICA-NeRF/assets/44490315/8c5eb266-ac37-41ba-9189-3d600402c3ce)

**Comment by Dongjiahua** [comment]
Hi, thanks for your comments! You can try to downscale the image with factor 2 by 
```
<original command> nerfstudio-data --downscale-factor 2
```
In addition, you may need to try different random seeds or apply our "control" mode to achieve similar results. This prompt's editing result is more diverse.
