### ISSUE TITLE
I cannot reproduce the results :)

### ISSUE THREAD

**Issue by sararoma95** [Dongjiahua/VICA-NeRF#3]
Hi,

Thanks for this great work.

I was trying to use your code and reproduce the results, but so far I'm not able to. Could you please guide me where/how to debug the problem, because I literally use 'Turn him into iron man' prompt, and results are not comparable with the ones in the paper. I'm using Nerfstudio 1.0.0

Thanks for your help!

<img width="1424" alt="image" src="https://github.com/Dongjiahua/VICA-NeRF/assets/95563069/5667d093-5178-4e49-9a18-06f19bc08588">

**Comment by Dongjiahua** [comment]
Thanks for your comments! Have you tried to downscale the image using 
```
nerfstudio-data --downscale-factor 2
```
Maybe the diffusion model doesn't get input with good shape.
